<a href="https://colab.research.google.com/github/ProstoRav/Py_HW/blob/main/HW_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task №44
В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без
<ins>get_dummies?</ins>

```
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()
```
### [Статья про one hot вид](https://colab.research.google.com/drive/1qKamnDiRmpRZkpiqWPkunBdAhmzhMcGz?usp=sharing)

In [27]:
import pandas as pd

In [43]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  robot
2  human
3  robot
4  human

In [44]:
pd.get_dummies(data['whoAmI']).head()

   human  robot
0      0      1
1      0      1
2      1      0
3      0      1
4      1      0

In [46]:
data = pd.DataFrame({'human': data['whoAmI'] == 'human', 'robot': data['whoAmI'] == 'robot'}).astype(int)
data.head()

   human  robot
0      0      1
1      0      1
2      1      0
3      0      1
4      1      0